spring.application.name=Pet-NotesAPI-BackEnd

# PostgreSQL
spring.jpa.database=postgresql
spring.datasource.url=${POSTGRES_URL_NaPi2178e872}
spring.datasource.username=${POSTGRES_USER_NaPi2178e872}
spring.datasource.password=${POSTGRES_PASSWORD_NaPi2178e872}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true


# SPRINGDOC / SWAGGER CONFIGURATION
# ???????? endpoint OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true

# Swagger UI
server.forward-headers-strategy=framework
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.url=/v3/api-docs

# ?????????? ???????
springdoc.swagger-ui.operations-sorter=method

# ?????????? ?????
# springdoc.swagger-ui.tag-sorter=alpha


